stages:
  - build
  - deploy

build:
  image: pandoc/minimal
  stage: build
  script:
    - |+
      for f in $(find . -type f -name '*.md'); do
        if [ ! -f "${f%.md}.html" ]; then
          pandoc "${f}" -o "${f%.md}.html" -s --template=template.html
        fi
      done

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - main