variables:
  FILES_TO_COMPRESS: "html js css svg"

pages:
  image: alpine:latest
  before_script:
    - apk update && apk add gzip brotli
  script:
    - mkdir -p .public .public/css
    - cp favicon.svg index.html script.min.js script.min.js.map .public/
    - cp css/styles.min.css .public/css/
    - mv .public public
    - for ext in $FILES_TO_COMPRESS; do find public -type f -name "*.$ext" -exec gzip -f -k {} \;; done
    - for ext in $FILES_TO_COMPRESS; do find public -type f -name "*.$ext" -exec brotli -f -k {} \;; done
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
