stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: pandoc/core
    entrypoint: ["/bin/sh", "-c"]
  script:
    - |+
      pandoc --version
      for f in $(find . -type f -name '*.md' ! -name 'README.md'); do
        filename=$(basename "$f" .md);
        echo filename;
        if [ ! -f "$filename.html" ]; then
          pandoc -f markdown -t html "$f" -o "$filename.html" -s --template=template.html;
        fi
      done

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - main