name: Build and Publish Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: create file list
        id: files_list
        run: |
              echo "files=$(find . -type f -name '*.md' ! -name 'README.md' -printf '"%p" ')" > $GITHUB_OUTPUT
      - name: Set up pandoc
        run: mkdir public
        uses: docker://pandoc/core
        with:
          args: >-
            ${{ steps.files_list.outputs.files }}
            -f markdown
            -t html
            --lua-filter=pandoc/fr-nbsp.lua
            -o ".public/$filename.html"
            -s --template=pandoc/template.html
      - name: Publish pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public